#!/usr/bin/env perl

#
# Ingo Schröder
#

$cmd=$0;
$cmd=~s/(.*\/)*//;
$purpouse = "";
$Usage=
"NAME

  $cmd - $purpouse

SYNOPSIS

  $cmd OPTIONS

OPTIONS

  -h          display this help
  -v   <uint> verbosity level [1]
  -l <string> lexicon file [none]
  -r    <int> rare word threshold [5]


VERSION


  ACOPOST 2.0.0 <https://github.com/acopost/acopost>
  Copyright (c) 2007-2016, ACOPOST Developers Team
  Copyright (c) 2001-2002, Ingo Schröder
";

use Getopt::Long;
Getopt::Long::Configure(qw( auto_abbrev no_ignore_case ));

sub usage
{
    print $Usage;
}

$rwt = 5;
$lexicon_file = "";
GetOptions
(
 'r=i' => \$rwt,
 'l=s' => \$lexicon_file,
 'h|help'        => sub { usage (); exit },
);

die $Usage if $lexicon_file eq "";

open(F, "<$lexicon_file") || die "can't open \"$lexicon_file\": $!\n";
LINE:
while ($l=<F>) {
  chomp($l);
  next LINE if $l=~m/^%%/;
  next LINE if $l=~m/^@/;
  if ($l=~m/^\S+\s+(.*)\s+(\d+)$/) {
    if ($2<=$rwt) {
      @as=split(/\s+/, $1);
      for (my $i=0; $i<=$#as; $i+=2) {
	$count{$as[$i]}+=$as[$i+1];
      }
    }
  } else {
    die "can't parse line \"$l\"\n";
  }
}
close(F);

foreach $t (keys %count) {
  printf "%d\n", $count{$t};
}
